version: '3.8'

services:
  mongodb:
    image: koloje/fyp-mongo:latest
    ports:
      - "27017:27017"

  backend:
    image: koloje/fyp-backend:prototype 
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb

  