version: '3.8'

services:
  backend:
    image: backend-image
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
